/**
 * Analysis Result Component
 * 
 * Main component that displays complete safety analysis.
 */

import type { SafetyAnalysisResult } from '@/lib/schemas';
import { RiskBadge } from '@/components/ui/RiskBadge';
import { RiskScoreGauge } from '@/components/ui/RiskScoreGauge';
import { RiskProgressBar } from '@/components/ui/RiskProgressBar';
import { KeySignals } from './KeySignals';
import { FactChecksList } from './FactChecksList';
import { RISK_LEVEL_CONFIG } from '@/lib/risk-utils';

interface AnalysisResultProps {
  result: SafetyAnalysisResult;
  useGauge?: boolean;
}

export function AnalysisResult({
  result,
  useGauge = true,
}: AnalysisResultProps) {
  const levelConfig = RISK_LEVEL_CONFIG[result.risk_level];
  
  return (
    <div className="space-y-6">
      {/* Header with risk score */}
      <div className="flex flex-col items-center gap-4 pb-6 border-b border-gray-200">
        {useGauge ? (
          <RiskScoreGauge score={result.risk_score} size={120} />
        ) : (
          <div className="w-full max-w-xs">
            <RiskProgressBar score={result.risk_score} />
          </div>
        )}
        
        <div className="flex flex-col items-center gap-2">
          <RiskBadge riskLevel={result.risk_level} size="lg" />
          <p className="text-sm text-gray-600 text-center">
            {levelConfig.description}
          </p>
        </div>
      </div>
      
      {/* Summary */}
      <div className="space-y-2">
        <h3 className="text-sm font-semibold text-gray-900 uppercase tracking-wide">
          Analysis Summary
        </h3>
        <p className="text-sm text-gray-700 leading-relaxed">
          {result.summary}
        </p>
      </div>
      
      {/* Verification & Confidence Row */}
      {(result.verification_status || result.confidence_score !== undefined) && (
        <div className="flex flex-wrap gap-3">
          {result.verification_status && result.verification_status !== 'not_applicable' && (
            <div className={`
              inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium
              ${result.verification_status === 'verified' ? 'bg-green-100 text-green-700' : ''}
              ${result.verification_status === 'unverified' ? 'bg-yellow-100 text-yellow-700' : ''}
              ${result.verification_status === 'contradicted' ? 'bg-red-100 text-red-700' : ''}
            `}>
              <span className="w-1.5 h-1.5 rounded-full bg-current" />
              {result.verification_status === 'verified' && 'Claims Verified'}
              {result.verification_status === 'unverified' && 'Claims Unverified'}
              {result.verification_status === 'contradicted' && 'Claims Contradicted'}
            </div>
          )}
          {result.confidence_score !== undefined && (
            <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium bg-gray-100 text-gray-700">
              Confidence: {Math.round(result.confidence_score * 100)}%
            </div>
          )}
        </div>
      )}
      
      {/* User Guidance */}
      {result.user_guidance && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
          <p className="text-sm text-blue-800">
            💡 {result.user_guidance}
          </p>
        </div>
      )}
      
      {/* Key Signals */}
      {result.key_signals && result.key_signals.length > 0 && (
        <KeySignals signals={result.key_signals} />
      )}
      
      {/* Fact Checks */}
      {result.fact_checks && result.fact_checks.length > 0 && (
        <FactChecksList factChecks={result.fact_checks} />
      )}
      
      {/* AI Disclaimer */}
      <div className="pt-4 border-t border-gray-200">
        <p className="text-xs text-gray-500 italic">
          This analysis was generated by AI ({result.model_version || 'Gemini'}) and should be used as a decision-support tool, not a definitive authority. Always exercise your own judgment.
        </p>
      </div>
    </div>
  );
}
